name: The Italian Travel Boutique
favicon: null
layout_spectrum: 0.5833463037852198
typography_spectrum: 0.6834292544517666
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8cb91'
    - '#140e10'
    - '#c38e40'
    - '#8c5921'
    - '#ffa44b'
  brandStrength: 0.25
  lightness: 0.3173310130368918
  saturation: 0.1875
  rhythmicContrast: 0.5197738050483167
purpose: []
