name: Travel with style
favicon: null
layout_spectrum: 0.5833463037852198
typography_spectrum: 0.6834292544517666
title: The Italian travel boutique
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#767676'
    - '#ffffff'
    - '#d6d6d6'
    - '#141414'
    - '#939393'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
