name: Travel with style
favicon: null
layout_spectrum: 0.5833463037852198
typography_spectrum: 0.6834292544517666
title: The Italian travel boutique
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#f08a90'
    - '#690e0a'
    - '#c4433a'
    - '#cdc3be'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
